-- | Premultiplication over every (channel value, alpha) pair, and data
-- textures left byte-for-byte unchanged.
--
-- The input is a 256 × 256 RGBA8 image in which the texel at column c and row
-- a has alpha a and colour channels c, 255 − c and c XOR 0x5A, so each channel
-- meets every alpha with every value. JuicyPixels' encoder writes it; only the
-- decoder is under test, and the expected values come from the straight
-- texels and the independent reference.
module Test.Asset.Image.Premultiply (spec) where

import Codec.Picture (PixelRGBA8 (..), encodePng, generateImage)
import Control.Monad (forM_, unless)
import Data.Bits (xor)
import qualified Data.ByteString as ByteString
import qualified Data.ByteString.Lazy as Lazy
import Hetoimasia.Asset (Asset (..), AssetId (..), Provenance (..))
import Hetoimasia.Asset.Image (DecodedImage (..), ImageKind (..))
import Test.Asset.Image.Support (Texel, decodeFully, referencePremultiplied, texels)
import Test.Hspec (Spec, describe, expectationFailure, it, shouldBe)

straight ∷ Int → Int → Texel
straight c a = (byte c, byte (255 - c), byte c `xor` 0x5A, byte a)
  where
    byte = fromIntegral

allPairs ∷ ByteString.ByteString
allPairs = Lazy.toStrict (encodePng (generateImage pixel 256 256))
  where
    pixel c a = let (r, g, b, alpha) = straight c a in PixelRGBA8 r g b alpha

asset ∷ Asset
asset = Asset (AssetId "every (channel, alpha) pair") (FromMemory "generated by Test.Asset.Image.Premultiply")

expected ∷ [Texel]
expected = [straight c a | a ← [0 .. 255], c ← [0 .. 255]]

spec ∷ Spec
spec = describe "Premultiplication" $ do
  it "keeps every colour channel within one code value of the reference, for every (value, alpha) pair" $
    decodedAs ColourImage $ \image →
      check image $ \(r, g, b, a) (r', g', b', a') →
        a' == a && all (\(c, c') → abs (fromIntegral c' - referencePremultiplied a c) <= 1) [(r, r'), (g, g'), (b, b')]
  it "leaves every texel exactly unchanged at alpha 255" $
    decodedAs ColourImage $ \image →
      check image $ \texel@(_, _, _, a) stored → a /= 255 || stored == texel
  it "makes every colour channel exactly zero at alpha 0" $
    decodedAs ColourImage $ \image →
      check image $ \(_, _, _, a) stored → a /= 0 || stored == (0, 0, 0, 0)
  it "leaves a data texture byte-for-byte unchanged, at every alpha" $
    decodedAs DataImage $ \image →
      decodedLevels image `shouldBe` [ByteString.pack (concatMap (\(r, g, b, a) → [r, g, b, a]) expected)]
  where
    decodedAs kind body =
      decodeFully kind asset allPairs >>= \case
        Left refusal → expectationFailure ("refused: " <> show refusal)
        Right image → body image

-- | Every texel satisfies the property against its straight texel; the
-- first that does not is reported.
check ∷ DecodedImage → (Texel → Texel → Bool) → IO ()
check image property = do
  length (texels image) `shouldBe` length expected
  forM_ (zip expected (texels image)) $ \(texel, stored) →
    unless (property texel stored) $
      expectationFailure ("straight " <> show texel <> " decoded to " <> show stored)
