-- | The shader compiler this package trusts, and how a shader reaches it.
--
-- D-11 keeps Synarchy's workflow — GLSL compiled while the Haskell build runs,
-- the SPIR-V embedded in the program — and P-9 requires that the compiler be
-- the pinned one and that a change to it rebuild what it compiled. GHC does
-- not notice an executable changing merely because a splice once ran it, and
-- Cabal does not notice a file a splice depends on unless the package lists
-- it. So the compiler's identity is written into a file before every build,
-- the /fingerprint/, which every splice registers as a dependency and which
-- the package's @**/*.fingerprint@ source glob makes Cabal watch.
--
-- The fingerprint is generated by @hetoimasia-shader-fingerprint@, this
-- package's own executable, from the private-prefix @glslangValidator@ wrapper
-- VK-4 provisions and the native manifest that records it. It carries:
--
-- * the target environment and the compiler flags, from 'configuredTarget'
--   and 'compilerFlags' below — the one place either is declared;
-- * the wrapper, by path and digest;
-- * the compiler the wrapper runs, by version, path and digest;
-- * the native manifest, by path and by the identity @native.py@ gives it:
--   the SHA-256 of the file.
--
-- Nothing here trusts a fingerprint it was handed. 'loadToolchain' reads one
-- and observes the live wrapper, compiler and manifest again, and refuses
-- unless they are what it records; the generator observes the same way and
-- refuses unless the wrapper, the compiler and the manifest agree with each
-- other. The wrapper is only ever found through the fingerprint or through
-- @HETOIMASIA_GLSLANG@, which @tools/native/native.py prepare@ exports. @PATH@
-- is never searched for a compiler, and the compiler runs with a @PATH@ this
-- module decides: the wrapper's own directory ahead of @\/usr\/bin:\/bin@, which
-- is where its @#!\/usr\/bin\/env bash@ line finds its shell.
--
-- The compile itself needs no display, device, loader or consent: it is a
-- child process that reads source text and writes SPIR-V. 'compileShader' is
-- the entry the Template Haskell adapter in
-- "Hetoimasia.GPU.Vulkan.Native.Shader" calls, and it is callable at run time
-- too, which is how its diagnostics are tested.
module Hetoimasia.GPU.Vulkan.Native.Shader.Toolchain
  ( -- * The compile configuration
    TargetEnvironment
  , vulkan13
  , targetEnvironmentName
  , configuredTarget
  , compilerFlags
  , ShaderStage (..)
  , stageName
  , stageDescription

    -- * The fingerprint
  , Fingerprint (..)
  , fingerprintPath
  , renderFingerprint
  , parseFingerprint
  , FingerprintInputs (..)
  , generateFingerprint
  , writeFingerprint

    -- * The trusted toolchain
  , Toolchain
  , toolchainFingerprint
  , loadToolchain
  , ToolchainFailure (..)
  , renderToolchainFailure

    -- * Compiling
  , ShaderSite (..)
  , ShaderSource (..)
  , CompileRequest (..)
  , CompiledShader (..)
  , ShaderFailure (..)
  , renderShaderFailure
  , compileShader
  ) where

import Control.Exception (IOException, try)
import Control.Monad (unless, when)
import Control.Monad.Trans.Class (lift)
import Control.Monad.Trans.Except (ExceptT (..), runExceptT, throwE)
import Crypto.Hash.SHA256 qualified as SHA256
import Data.ByteString (ByteString)
import Data.ByteString qualified as ByteString
import Data.ByteString.Builder (byteStringHex, toLazyByteString)
import Data.ByteString.Lazy qualified as Lazy
import Data.ByteString.Lazy.Char8 qualified as LazyChar8
import Data.List (intercalate, isPrefixOf, nub)
import Data.Maybe (fromMaybe)
import System.Directory
  ( canonicalizePath
  , createDirectoryIfMissing
  , doesFileExist
  , executable
  , getPermissions
  , renameFile
  )
import System.Environment (lookupEnv)
import System.Exit (ExitCode (..))
import System.FilePath
  ( dropTrailingPathSeparator
  , isAbsolute
  , isRelative
  , makeRelative
  , splitDirectories
  , takeDirectory
  , (<.>)
  , (</>)
  )
import System.IO (IOMode (ReadMode, WriteMode), hGetContents', hPutStr, hSetEncoding, utf8, withFile)
import System.IO.Temp (withSystemTempDirectory)
import System.Process (CreateProcess (cwd, env), proc, readCreateProcessWithExitCode)

import Hetoimasia.GPU.Vulkan.Native.Shader.Json (member, parseJson, stringMember)

-- --------------------------------------------------------------------------
-- The compile configuration

-- | The Vulkan environment a shader is compiled for, passed to the compiler
-- as @--target-env@. D-12 requires Vulkan 1.3, and 'vulkan13' is the only
-- value: adding one is a deliberate edit here, which moves the fingerprint.
newtype TargetEnvironment = TargetEnvironment String
  deriving (Eq, Show)

-- | Vulkan 1.3, whose SPIR-V is version 1.6.
vulkan13 ∷ TargetEnvironment
vulkan13 = TargetEnvironment "vulkan1.3"

-- | The name the compiler is given.
targetEnvironmentName ∷ TargetEnvironment → String
targetEnvironmentName (TargetEnvironment name) = name

-- | The target environment the fingerprint is generated for, and so the one a
-- splice may compile for.
configuredTarget ∷ TargetEnvironment
configuredTarget = vulkan13

-- | The flags every compile passes besides the target, the stage and the file
-- names: SPIR-V under Vulkan semantics. The target environment would imply
-- @-V@; it is stated anyway so the fingerprint says what the command line
-- says.
compilerFlags ∷ [String]
compilerFlags = ["-V"]

-- | A pipeline stage. The compiler is told the stage rather than left to guess
-- it from a file name, so an inline source and a file compile the same way.
data ShaderStage = Vertex | Fragment | Compute
  deriving (Eq, Show, Enum, Bounded)

-- | The stage as the compiler's @-S@ names it.
stageName ∷ ShaderStage → String
stageName = \case
  Vertex → "vert"
  Fragment → "frag"
  Compute → "comp"

-- | The stage as a diagnostic names it.
stageDescription ∷ ShaderStage → String
stageDescription = \case
  Vertex → "vertex shader"
  Fragment → "fragment shader"
  Compute → "compute shader"

-- --------------------------------------------------------------------------
-- The fingerprint

-- | Everything a compile depends on besides its own source and includes.
--
-- Two fingerprints are equal exactly when a shader compiled under one would
-- be compiled identically under the other, which is why a changed field is
-- what makes a splice run again.
data Fingerprint = Fingerprint
  { fingerprintTarget ∷ String
  , fingerprintFlags ∷ [String]
  , fingerprintWrapper ∷ FilePath
  , fingerprintWrapperSha256 ∷ String
  , fingerprintVersion ∷ String
  , fingerprintCompiler ∷ FilePath
  , fingerprintCompilerSha256 ∷ String
  , fingerprintManifest ∷ FilePath
  , fingerprintManifestSha256 ∷ String
  }
  deriving (Eq, Show)

-- | Where a package's fingerprint lives, relative to the package's root: the
-- directory Cabal runs the compiler in, and so the one a splice resolves
-- relative paths against.
fingerprintPath ∷ FilePath
fingerprintPath = "shaders" </> "toolchain.fingerprint"

formatVersion ∷ String
formatVersion = "1"

-- | The fingerprint as its file holds it: one @key value@ line per field.
renderFingerprint ∷ Fingerprint → String
renderFingerprint fingerprint =
  unlines $
    [ "# The shader toolchain fingerprint, generated by hetoimasia-shader-fingerprint"
    , "# before every build. Do not edit or commit it: every shader splice checks it"
    , "# against the wrapper, compiler and native manifest it names, and refuses a"
    , "# fingerprint they no longer match."
    ]
      <> [key <> " " <> value | (key, value) ← fields fingerprint]

fields ∷ Fingerprint → [(String, String)]
fields fingerprint =
  [ ("format", formatVersion)
  , ("target-env", fingerprintTarget fingerprint)
  , ("flags", unwords (fingerprintFlags fingerprint))
  , ("wrapper", fingerprintWrapper fingerprint)
  , ("wrapper-sha256", fingerprintWrapperSha256 fingerprint)
  , ("glslang", fingerprintVersion fingerprint)
  , ("compiler", fingerprintCompiler fingerprint)
  , ("compiler-sha256", fingerprintCompilerSha256 fingerprint)
  , ("native-manifest", fingerprintManifest fingerprint)
  , ("native-manifest-sha256", fingerprintManifestSha256 fingerprint)
  ]

-- | Read a fingerprint back. Every field is required exactly once, and an
-- unknown key or format is refused rather than skipped: a reader that ignored
-- what it did not recognize could accept a file written for some other
-- configuration.
parseFingerprint ∷ String → Either String Fingerprint
parseFingerprint text = do
  pairs ← traverse entry [line | line ← lines text, not (null line), not ("#" `isPrefixOf` line)]
  let known = map fst (fields empty)
      unknown = [key | (key, _) ← pairs, key `notElem` known]
      repeated = [key | key ← known, length (filter ((== key) . fst) pairs) > 1]
  unless (null unknown) (Left ("unknown fields " <> unwords unknown))
  unless (null repeated) (Left ("repeated fields " <> unwords repeated))
  let get key = maybe (Left ("no " <> key <> " field")) Right (lookup key pairs)
  format ← get "format"
  unless (format == formatVersion) (Left ("format " <> format <> ", not " <> formatVersion))
  Fingerprint
    <$> get "target-env"
    <*> (words <$> get "flags")
    <*> get "wrapper"
    <*> get "wrapper-sha256"
    <*> get "glslang"
    <*> get "compiler"
    <*> get "compiler-sha256"
    <*> get "native-manifest"
    <*> get "native-manifest-sha256"
  where
    entry line = case break (== ' ') line of
      (key, ' ' : value) → Right (key, value)
      _ → Left ("a line with no value: " <> line)
    empty = Fingerprint "" [] "" "" "" "" "" "" ""

-- | Where the generator is told to look. Each is optional because each has
-- the environment @native.py prepare@ exports as its default; neither has a
-- default beyond that.
data FingerprintInputs = FingerprintInputs
  { inputWrapper ∷ Maybe FilePath
  -- ^ The wrapper; otherwise @HETOIMASIA_GLSLANG@.
  , inputManifest ∷ Maybe FilePath
  -- ^ The native manifest; otherwise the one beside @HETOIMASIA_VULKAN_PREFIX@.
  }

-- | Observe the wrapper, the compiler and the native manifest, require that
-- they agree, and describe them as a fingerprint for 'configuredTarget'.
generateFingerprint ∷ FingerprintInputs → IO (Either ToolchainFailure Fingerprint)
generateFingerprint inputs = runExceptT $ do
  wrapper ← named (inputWrapper inputs) glslangVariable $ \value → pure (Just value)
  manifest ← named (inputManifest inputs) prefixVariable $ \value →
    pure (Just (takeDirectory (dropTrailingPathSeparator value) </> manifestName))
  ExceptT (observe wrapper manifest)
  where
    named (Just value) _ _ = pure value
    named Nothing variable derive = do
      found ← lift (lookupEnv variable)
      derived ← lift (maybe (pure Nothing) derive (nonEmpty found))
      maybe (throwE (unconfigured variable)) pure derived
    nonEmpty = \case
      Just value | not (null value) → Just value
      _ → Nothing
    unconfigured variable =
      refusal
        ( variable
            <> " is not set and nothing else was named. Run `python3 tools/native/native.py prepare` \
               \and use what it exports, or pass the path explicitly; PATH is never searched"
        )

-- | Write the fingerprint, unless the file already says exactly this. An
-- unchanged fingerprint is left alone — not even rewritten with the same
-- bytes — so Cabal and GHC see nothing to rebuild. Says whether it wrote.
writeFingerprint ∷ FilePath → Fingerprint → IO Bool
writeFingerprint path fingerprint = do
  let rendered = renderFingerprint fingerprint
  present ← doesFileExist path
  existing ← if present then Just <$> readUtf8 path else pure Nothing
  if existing == Just rendered
    then pure False
    else do
      createDirectoryIfMissing True (takeDirectory path)
      let staging = path <.> "partial"
      writeFileUtf8 staging rendered
      renameFile staging path
      pure True

-- --------------------------------------------------------------------------
-- The trusted toolchain

-- | A fingerprint that 'loadToolchain' has checked against the live wrapper,
-- compiler and manifest. There is no other way to make one.
newtype Toolchain = Toolchain Fingerprint

-- | What the toolchain was checked against.
toolchainFingerprint ∷ Toolchain → Fingerprint
toolchainFingerprint (Toolchain fingerprint) = fingerprint

-- | Why the shader toolchain was refused, and what was being looked for.
data ToolchainFailure = ToolchainFailure
  { refusalReason ∷ String
  , refusalWrapper ∷ Maybe FilePath
  -- ^ The wrapper looked for, where one was named.
  , refusalManifest ∷ Maybe FilePath
  -- ^ The native manifest looked for, where one was named.
  , refusalManifestIdentity ∷ Maybe String
  -- ^ The native manifest identity the wrapper was held to: the one a
  -- fingerprint recorded, or, while generating one, the manifest's own.
  }
  deriving (Eq, Show)

refusal ∷ String → ToolchainFailure
refusal reason = ToolchainFailure reason Nothing Nothing Nothing

-- | A refusal as a build reports it.
renderToolchainFailure ∷ ToolchainFailure → String
renderToolchainFailure failure =
  intercalate "\n" $
    ["the shader toolchain is refused: " <> refusalReason failure]
      <> ["  glslangValidator wrapper: " <> wrapper | Just wrapper ← [refusalWrapper failure]]
      <> [ "  native manifest: " <> manifest <> maybe "" (\identity → " (expected identity " <> identity <> ")") (refusalManifestIdentity failure)
         | Just manifest ← [refusalManifest failure]
         ]
      <> [ "  No other glslangValidator is used. Regenerate the fingerprint from the provisioned prefix with"
         , "  `bash tools/vulkan/run.sh build hetoimasia-gpu-vulkan-native`, or see packages/gpu-vulkan/native/README.md."
         ]

-- | Read a fingerprint and hold it to the wrapper, compiler and manifest it
-- names, observed now. It is refused when it is missing, malformed, generated
-- for another configuration or another wrapper than @HETOIMASIA_GLSLANG@
-- names, or when anything it records has changed since.
loadToolchain ∷ FilePath → IO (Either ToolchainFailure Toolchain)
loadToolchain path = runExceptT $ do
  present ← lift (doesFileExist path)
  unless present $
    throwE (refusal ("no shader toolchain fingerprint at " <> path <> "; it is generated before every build"))
  recorded ← either (throwE . malformed) pure . parseFingerprint =<< lift (readUtf8 path)
  let expecting ∷ ToolchainFailure → ToolchainFailure
      expecting failure =
        failure
          { refusalWrapper = Just (fingerprintWrapper recorded)
          , refusalManifest = Just (fingerprintManifest recorded)
          , refusalManifestIdentity = Just (fingerprintManifestSha256 recorded)
          }
  unless
    (fingerprintTarget recorded == targetEnvironmentName configuredTarget && fingerprintFlags recorded == compilerFlags)
    $ throwE . expecting . refusal
    $ "the fingerprint at "
      <> path
      <> " records target "
      <> fingerprintTarget recorded
      <> " with flags "
      <> show (fingerprintFlags recorded)
      <> ", but this adapter compiles for "
      <> targetEnvironmentName configuredTarget
      <> " with flags "
      <> show compilerFlags
  exported ← lift (lookupEnv glslangVariable)
  case exported of
    Just named
      | not (null named)
      , named /= fingerprintWrapper recorded →
          throwE . expecting . refusal $
            glslangVariable
              <> " names the wrapper "
              <> named
              <> ", but the fingerprint at "
              <> path
              <> " was generated for another one"
    _ → pure ()
  observed ← either (throwE . expecting) pure =<< lift (observe (fingerprintWrapper recorded) (fingerprintManifest recorded))
  let changed =
        [ key <> " is now " <> now <> ", not the recorded " <> was
        | ((key, was), (_, now)) ← zip (fields recorded) (fields observed)
        , was /= now
        ]
  unless (null changed) $
    throwE . expecting . refusal $
      "the fingerprint at " <> path <> " no longer describes the toolchain: " <> intercalate "; " changed
  pure (Toolchain recorded)
  where
    malformed problem = refusal ("the fingerprint at " <> path <> " is malformed (" <> problem <> ")")

glslangVariable, prefixVariable, manifestName, identityFlag ∷ String
glslangVariable = "HETOIMASIA_GLSLANG"
prefixVariable = "HETOIMASIA_VULKAN_PREFIX"
manifestName = "hetoimasia-native-manifest.json"
-- The wrapper answers this itself, compiling nothing; see tools/native/vulkan.py.
identityFlag = "--hetoimasia-identity"

-- | The wrapper, the compiler and the manifest as they are now, required to
-- agree with each other: the manifest must record this wrapper, the wrapper's
-- bytes and the compiler's must be the ones it recorded, and the wrapper must
-- answer for the recorded compiler.
observe ∷ FilePath → FilePath → IO (Either ToolchainFailure Fingerprint)
observe wrapper manifest = runExceptT $ do
  -- The manifest is read first so that every refusal after it can name the
  -- identity the wrapper was being held to, including one for a missing
  -- wrapper.
  manifestBytes ←
    either
      (\problem → throwE (ToolchainFailure ("the native manifest " <> manifest <> " is unreadable (" <> show problem <> ")") (Just wrapper) (Just manifest) Nothing))
      pure
      =<< lift (try @IOException (ByteString.readFile manifest))
  let manifestSha256 = hex (SHA256.hash manifestBytes)
      refuse ∷ String → ExceptT ToolchainFailure IO a
      refuse reason = throwE (ToolchainFailure reason (Just wrapper) (Just manifest) (Just manifestSha256))
  unless (isAbsolute wrapper) $
    refuse ("the glslangValidator wrapper " <> wrapper <> " is not an absolute path")
  wrapperPresent ← lift (doesFileExist wrapper)
  unless wrapperPresent $
    refuse ("no glslangValidator wrapper at " <> wrapper)
  permissions ← lift (getPermissions wrapper)
  unless (executable permissions) $
    refuse ("the glslangValidator wrapper at " <> wrapper <> " is not executable")
  document ←
    either (\problem → refuse ("the native manifest " <> manifest <> " is not JSON (" <> problem <> ")")) pure
      =<< lift (parseJson <$> readUtf8 manifest)
  let record = member "vulkan" document >>= member "glslang"
      recorded key =
        maybe (refuse ("the native manifest " <> manifest <> " records no glslang " <> key)) pure (record >>= stringMember key)
  recordedWrapper ← recorded "wrapper"
  recordedWrapperSha256 ← recorded "wrapper_sha256"
  recordedVersion ← recorded "version"
  recordedCompiler ← recorded "compiler"
  recordedCompilerSha256 ← recorded "compiler_sha256"
  sameWrapper ← lift ((==) <$> canonicalizePath recordedWrapper <*> canonicalizePath wrapper)
  unless sameWrapper $
    refuse ("the native manifest " <> manifest <> " records the wrapper " <> recordedWrapper <> ", not " <> wrapper)
  wrapperSha256 ← lift (sha256File wrapper)
  when (wrapperSha256 /= recordedWrapperSha256) $
    refuse
      ( "the glslangValidator wrapper at "
          <> wrapper
          <> " hashes to "
          <> wrapperSha256
          <> ", not the recorded "
          <> recordedWrapperSha256
      )
  answered ← lift (try @IOException (readCreateProcessWithExitCode (compilerProcess wrapper [identityFlag]) ""))
  reported ← case answered of
    Left problem → refuse ("the glslangValidator wrapper at " <> wrapper <> " could not be run (" <> show problem <> ")")
    Right (ExitSuccess, out, _) → pure [(key, value) | line ← lines out, (key, ' ' : value) ← [break (== ' ') line]]
    Right (status, _, err) →
      refuse ("the glslangValidator wrapper at " <> wrapper <> " exited " <> show status <> " for " <> identityFlag <> ": " <> err)
  let disagreements =
        [ "it reports " <> key <> " " <> fromMaybe "nothing" (lookup key reported) <> ", but the manifest records " <> value
        | (key, value) ← [("glslang", recordedVersion), ("compiler", recordedCompiler), ("sha256", recordedCompilerSha256)]
        , lookup key reported /= Just value
        ]
  unless (null disagreements) $
    refuse ("the glslangValidator wrapper at " <> wrapper <> " does not answer for the recorded compiler: " <> intercalate "; " disagreements)
  compilerSha256 ←
    either (\problem → refuse ("the compiler " <> recordedCompiler <> " is unreadable (" <> show problem <> ")")) pure
      =<< lift (try @IOException (sha256File recordedCompiler))
  when (compilerSha256 /= recordedCompilerSha256) $
    refuse
      ( "the compiler at "
          <> recordedCompiler
          <> " hashes to "
          <> compilerSha256
          <> ", not the recorded "
          <> recordedCompilerSha256
      )
  pure
    Fingerprint
      { fingerprintTarget = targetEnvironmentName configuredTarget
      , fingerprintFlags = compilerFlags
      , fingerprintWrapper = wrapper
      , fingerprintWrapperSha256 = wrapperSha256
      , fingerprintVersion = recordedVersion
      , fingerprintCompiler = recordedCompiler
      , fingerprintCompilerSha256 = compilerSha256
      , fingerprintManifest = manifest
      , fingerprintManifestSha256 = manifestSha256
      }

-- | The wrapper as a child process: by absolute path, with a @PATH@ this
-- module chooses rather than the one the build inherited. The wrapper's own
-- directory comes first so anything it looks up by name is the prefix's; the
-- system directories after it hold the shell its @#!@ line names.
compilerProcess ∷ FilePath → [String] → CreateProcess
compilerProcess wrapper arguments =
  (proc wrapper arguments)
    { env = Just [("PATH", takeDirectory wrapper <> ":/usr/bin:/bin"), ("LC_ALL", "C")]
    }

sha256File ∷ FilePath → IO String
sha256File path = hex . SHA256.hashlazy <$> Lazy.readFile path

hex ∷ ByteString → String
hex = LazyChar8.unpack . toLazyByteString . byteStringHex

readUtf8 ∷ FilePath → IO String
readUtf8 path = withFile path ReadMode $ \handle → do
  hSetEncoding handle utf8
  hGetContents' handle

writeFileUtf8 ∷ FilePath → String → IO ()
writeFileUtf8 path text = withFile path WriteMode $ \handle → do
  hSetEncoding handle utf8
  hPutStr handle text

-- --------------------------------------------------------------------------
-- Compiling

-- | Where a shader was spliced: the module, and the file position of the
-- splice. A runtime caller names its own.
data ShaderSite = ShaderSite
  { siteModule ∷ String
  , siteFile ∷ FilePath
  , siteLine ∷ Int
  , siteColumn ∷ Int
  }
  deriving (Eq, Show)

-- | Source text, or a file relative to the package root. Only a file's
-- includes can be found relative to the file itself.
data ShaderSource
  = InlineSource String
  | SourceFile FilePath
  deriving (Eq, Show)

-- | One compile.
data CompileRequest = CompileRequest
  { requestSite ∷ ShaderSite
  , requestTarget ∷ TargetEnvironment
  , requestStage ∷ ShaderStage
  , requestIncludes ∷ [FilePath]
  -- ^ Include directories, relative to the package root.
  , requestSource ∷ ShaderSource
  }

-- | A compiled shader and what it was compiled from.
data CompiledShader = CompiledShader
  { compiledSpirv ∷ ByteString
  , compiledInputs ∷ [FilePath]
  -- ^ The source file, when there is one, and every include the compiler
  -- resolved, transitively, relative to the package root.
  , compiledWarnings ∷ [String]
  }

-- | A shader that did not compile, and where it came from.
data ShaderFailure = ShaderFailure
  { failureSite ∷ ShaderSite
  , failureStage ∷ ShaderStage
  , failureTarget ∷ TargetEnvironment
  , failureSource ∷ ShaderSource
  , failureProblem ∷ String
  , failureMessages ∷ [String]
  }
  deriving (Eq, Show)

-- | A failure as a build reports it: the stage, the module and the splice's
-- position, the source, and what the compiler said.
renderShaderFailure ∷ ShaderFailure → String
renderShaderFailure failure =
  intercalate "\n" $
    ( "the "
        <> stageDescription (failureStage failure)
        <> " spliced at "
        <> siteFile site
        <> ":"
        <> show (siteLine site)
        <> ":"
        <> show (siteColumn site)
        <> " in module "
        <> siteModule site
        <> " ("
        <> source
        <> ", target "
        <> targetEnvironmentName (failureTarget failure)
        <> ") did not compile: "
        <> failureProblem failure
    )
      : map ("    " <>) (failureMessages failure)
  where
    site = failureSite failure
    source = case failureSource failure of
      InlineSource _ → "inline source"
      SourceFile path → "source " <> path

-- | Compile one shader with the trusted toolchain. The package root is where
-- a source file, the include directories and the resolved includes are
-- relative to; an include resolved outside it is refused, because a source
-- distribution of the package would not carry it.
compileShader ∷ Toolchain → FilePath → CompileRequest → IO (Either ShaderFailure CompiledShader)
compileShader toolchain root request =
  withSystemTempDirectory "hetoimasia-shader" $ \scratch → runExceptT $ do
    let fingerprint = toolchainFingerprint toolchain
        stage = requestStage request
        fail' ∷ String → [String] → ExceptT ShaderFailure IO a
        fail' problem messages =
          throwE
            ShaderFailure
              { failureSite = requestSite request
              , failureStage = stage
              , failureTarget = requestTarget request
              , failureSource = requestSource request
              , failureProblem = problem
              , failureMessages = messages
              }
    unless (targetEnvironmentName (requestTarget request) == fingerprintTarget fingerprint) $
      fail'
        ("the toolchain fingerprint was generated for target " <> fingerprintTarget fingerprint)
        []
    input ← case requestSource request of
      InlineSource text → do
        let file = scratch </> "shader" <.> stageName stage
        lift (writeFileUtf8 file text)
        pure file
      SourceFile relative → do
        let file = root </> relative
        present ← lift (doesFileExist file)
        unless present (fail' ("there is no shader source at " <> file) [])
        pure file
    let output = scratch </> "shader.spv"
        depfile = scratch </> "shader.d"
        arguments =
          compilerFlags
            <> ["--target-env", targetEnvironmentName (requestTarget request)]
            <> ["-S", stageName stage]
            <> ["-I" <> (root </> directory) | directory ← requestIncludes request]
            <> ["--depfile", depfile, "-o", output, input]
    (status, out, err) ←
      lift (readCreateProcessWithExitCode (compilerProcess (fingerprintWrapper fingerprint) arguments) {cwd = Just scratch} "")
    let said = lines (out <> err)
        messages = [line | line ← said, any (`isPrefixOf` line) ["ERROR:", "WARNING:"]]
        warnings = [line | line ← said, "WARNING:" `isPrefixOf` line]
        compiler = "glslang " <> fingerprintVersion fingerprint
    case status of
      ExitFailure code →
        fail'
          (compiler <> " rejected it (exit " <> show code <> ")")
          (if null messages then filter (not . null) said else messages)
      ExitSuccess → do
        spirv ← lift (ByteString.readFile output)
        dependencies ← lift (depfileInputs <$> readUtf8 depfile)
        canonicalRoot ← lift (canonicalizePath root)
        canonicalInput ← lift (canonicalizePath input)
        resolved ← lift (traverse canonicalizePath dependencies)
        -- An inline source was written to a scratch file, which is not an
        -- input anyone could edit; a source file is.
        let scratchInput = case requestSource request of
              InlineSource _ → Just canonicalInput
              SourceFile _ → Nothing
            inputs = nub [path | path ← resolved, Just path /= scratchInput]
            outside = [path | path ← inputs, not (within canonicalRoot path)]
        unless (null outside) $
          fail'
            ("it includes " <> unwords outside <> ", outside the package root " <> canonicalRoot <> ", which a source distribution would not carry")
            []
        pure
          CompiledShader
            { compiledSpirv = spirv
            , compiledInputs = map (makeRelative canonicalRoot) inputs
            , compiledWarnings = warnings
            }
  where
    within directory path =
      let relative = makeRelative directory path
       in isRelative relative && ".." `notElem` splitDirectories relative

-- | The prerequisites a compiler's depfile lists: everything after the target,
-- with line continuations joined and escaped spaces kept inside a name.
depfileInputs ∷ String → [FilePath]
depfileInputs text = case breakTarget (joined text) of
  Nothing → []
  Just rest → names rest
  where
    joined = \case
      '\\' : '\n' : rest → ' ' : joined rest
      c : rest → c : joined rest
      [] → []
    breakTarget = \case
      ':' : ' ' : rest → Just rest
      ':' : '\n' : rest → Just rest
      _ : rest → breakTarget rest
      [] → Nothing
    names = go [] []
    go current found = \case
      '\\' : ' ' : rest → go (' ' : current) found rest
      c : rest
        | c `elem` (" \t\n" ∷ String) → go [] (push current found) rest
        | otherwise → go (c : current) found rest
      [] → reverse (push current found)
    push current found = if null current then found else reverse current : found
